# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Palindromic
email: naitian@mg.naitian.org
description: > # this means to ignore newlines until "baseurl:"
    A look into the Internet, software, and art that is my life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naitian.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NaitianZhou
github_username:  naitian

navigation:
    - title: home
      url: /
    - title: blog
      url: /blog/
      dir: true
    - title: projects
      url: /projects/
      dir: true
    - title: about
      url: /about/
      dir: false
    - title: art
      url: /art/
      dir: true

collections:
    projects:
        output: true
        permalink: /projects/:title/
    art:
        output: true
        permalink: /art/:title/

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            permalink: /:categories/:year/:month/:day/:title/
            layout: post
            custom_css:
                - post
    -
        scope:
            path: ""
            type: "projects"
        values:
            layout: project
            custom_css:
                - project_page
                - markdown
    -
        scope:
            path: ""
            type: "art"
        values:
            layout: art
            custom_css:
                - art_page
                - markdown


kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - package.json
  - node_modules/
  - gulpfile.js
  - _assets
